In [1]:
!pip3 install stable-baselines3[extra]

     -------------------------------------- 177.7/177.7 kB 5.2 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 16.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ------------------------------------- 935.2/935.2 kB 19.7 MB/s eta 0:00:00
     ---------------------------------------- 78.4/78.4 kB 4.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for gym: filename=gym-0.21.0-py3-none-any.whl size=1616823 sha256=4d10e8ecf5981cf5a2b294a440c02b37796fccdf32bf6c3c64e7af5c313b99ac
  Stored in directory: c:\users\c28ga\appdata\local\pip\cache\wheels\b3\50\6c\0a82c1358b4da2dbd9c1bb17

In [4]:
import os
import gym 
from stable_baselines3 import PPO # proximal policy optimization
from stable_baselines3.common.vec_env import DummyVecEnv # DummyVecEnv is a vectorized environment
from stable_baselines3.common.evaluation import evaluate_policy 

https://stable-baselines3.readthedocs.io/en/master/guide/rl.html
https://spinningup.openai.com/en/latest/spinningup/rl_intro2.html#a-taxonomy-of-rl-algorithms

In [6]:
environemt_name = 'CartPole-v0'
env = gym.make(environemt_name)

In [9]:
env.reset()
# outputs 4 values which are the state, the action, the reward, and the next state

(array([-0.04558912,  0.35278752, -0.04546512, -0.62989473], dtype=float32), 1.0, False, {})


In [12]:
print(env.action_space.sample())
# outputs a random action
print(env.action_space)

0
Discrete(2)


In [13]:
env.observation_space
# lower and upper bounds of the observation space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [18]:
print(env.step(1)) # take action 1
print(env.step(0)) # take action 0

(array([-0.00234193,  0.5529701 , -0.1239249 , -1.0404778 ], dtype=float32), 1.0, False, {})
(array([ 0.00871747,  0.3596928 , -0.14473446, -0.7891259 ], dtype=float32), 1.0, False, {})


In [21]:
episodes = 5
for episode in range(1,episodes+1): # play 5 games
    state = env.reset() #reset the environment to get back the initial state of observations
    done = False
    score = 0
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state,reward,done,info = env.step(action)
        score += reward
    print('Episode: {} Score: {}'.format(episode,score))
env.close()

Episode: 1 Score: 48.0
Episode: 2 Score: 13.0
Episode: 3 Score: 15.0
Episode: 4 Score: 36.0
Episode: 5 Score: 15.0


https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

In [22]:
env.action_space
#type of action space
# Actions:
# 0: left
# 1: right
# type: Discrete(2)

Discrete(2)

In [24]:
env.action_space.sample()
#example of action space


1

In [26]:
env.observation_space
#type of observation space
# type Box(4)
# Num   Observation     Min     Max
# 0     Cart Position  -4.8    4.8
# 1     Cart Velocity  -Inf    Inf
# 2     Pole Angle     -24deg  24 deg
# 3     Pole Velocity   -Inf  Inf

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [25]:
env.observation_space.sample()
#example of observation space

array([-1.4512579e+00,  5.8148958e+37, -1.6330791e-01, -2.9387652e+38],
      dtype=float32)

Model Based vs Model Free <br />
https://spinningup.openai.com/en/latest/spinningup/rl_intro2.html


Certain algorithms will perform better for certain environments.<br />
Alogrithm should map appropirately to your action space.<br />
https://stable-baselines.readthedocs.io/en/master/guide/algos.html

In [34]:
#Make directories first
log_path = os.path.join('Training','Logs')

In [35]:
log_path

'Training\\Logs'

In [36]:
env = gym.make(environemt_name) # creating environment
env = DummyVecEnv([lambda: env]) # creating a vectorized environment
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)
# Algorithm(Multy layer perceptron policy, dummy vectorised environment, verbose=1, tensorboard_log=True)

Using cpu device


In [32]:
PPO??

Init signature:
PPO(
    policy: Union[str, Type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gym.core.Env, stable_baselines3.common.vec_env.base_vec_env.VecEnv, str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    normalize_advantage: bool = True,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    target_kl: Optional[float] = None,
    tensorboard_log: Optional[str] = None,
    create_eval_env: bool = False,
    policy_kwargs: Optional[Dict[str, Any]] = None,
    verbose: int = 0,
    seed: Optional[int] = None,
    device: Union[torch.device, str] = 'auto',
    _init_setup_mode

In [37]:
 model.learn(total_timesteps=20000)
 # 20000 for a simple algorithm

Logging to Training\Logs\PPO_1
-----------------------------
| time/              |      |
|    fps             | 156  |
|    iterations      | 1    |
|    time_elapsed    | 13   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 210         |
|    iterations           | 2           |
|    time_elapsed         | 19          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008726128 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.00646    |
|    learning_rate        | 0.0003      |
|    loss                 | 7.14        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0164     |
|    value_loss           | 49.7        |
-----------------------------------------
---

In [38]:
PPO_Path = os.path.join('Training','Saved_Models','PPO_Model_CartPole')

In [39]:
model.save(PPO_Path)

In [40]:
del model

In [41]:
model = PPO.load(PPO_Path,env=env)

In [42]:
evaluate_policy(model,env,n_eval_episodes=10,render=True)
#output average reward,standard deviation

c:\Python\Python39\lib\site-packages\stable_baselines3\common\evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


(200.0, 0.0)

In [43]:
env.close()

In [45]:
model.predict(obs)

(array([1], dtype=int64), None)

In [46]:
episodes = 5
for episode in range(1,episodes+1): # play 5 games
    obs = env.reset() #reset the environment to get back the initial state of observations
    done = False
    score = 0
    while not done:
        env.render()
        action,_states = model.predict(obs)
        obs,reward,done,info = env.step(action)
        score += reward
    print('Episode: {} Score: {}'.format(episode,score))
env.close()

Episode: 1 Score: [200.]
Episode: 2 Score: [194.]
Episode: 3 Score: [200.]
Episode: 4 Score: [200.]
Episode: 5 Score: [200.]


In [47]:
obs = env.reset()

In [49]:
model.predict??

Signature:
model.predict(
    observation: numpy.ndarray,
    state: Optional[Tuple[numpy.ndarray, ...]] = None,
    episode_start: Optional[numpy.ndarray] = None,
    deterministic: bool = False,
) -> Tuple[numpy.ndarray, Optional[Tuple[numpy.ndarray, ...]]]
Source:   
    def predict(
        self,
        observation: np.ndarray,
        state: Optional[Tuple[np.ndarray, ...]] = None,
        episode_start: Optional[np.ndarray] = None,
        deterministic: bool = False,
    ) -> Tuple[np.ndarray, Optional[Tuple[np.ndarray, ...]]]:
        """
        Get the policy action from an observation (and optional hidden state).
        Includes sugar-coating to handle different observations (e.g. normalizing images).

        :param observation: the input observation
        :param state: The last hidden states (can be None, used in recurrent policies)
        :param episode_start: The last masks (can be None, used in recurrent policies)
            this correspond to beginning of episode